[tools]
go = "latest"
java = "latest"
node = "24"
pnpm = "latest"
python = "latest"
yarn = "latest"
rust = "latest"
bun = "latest"
npm = "latest"
uv = "latest"
zig = "latest"

# JSON utilities
"go:github.com/tomnomnom/gron" = "latest"
"go:github.com/josephburnett/jd" = "latest"

# CLI utilities
"go:github.com/junegunn/fzf" = "latest"
"go:github.com/antonmedv/watch" = "latest"
"go:github.com/monasticacademy/httptap" = "latest"
"go:github.com/charmbracelet/crush" = "latest"

# File finding utilities
"cargo:fd-find" = "latest"
"cargo:find-files" = "latest"

# Git utilities
"cargo:timeago-cli" = "latest"
"cargo:onefetch" = "latest"
"cargo:git-absorb" = "latest"

# Cargo utilities
"cargo:cargo-bump" = "latest"
"cargo:cargo-edit" = "latest"
"cargo:cargo-update" = "latest"
"cargo:cargo-make" = "latest"
"cargo:cargo-cache" = "latest"
"cargo:cargo-binstall" = "latest"

# CLI utilities
"cargo:rargs" = "latest"
"cargo:names" = "latest"
"cargo:tzupdate" = "latest"
"cargo:ripgrep" = "latest"
"cargo:xh" = "latest"
"cargo:gifski" = "latest"
"cargo:hyperfine" = "latest"
"cargo:lla" = "latest"
"cargo:rustic-rs" = "latest"
"cargo:tuc" = "latest"
"cargo:somo" = "latest"

# GitHub repositories
"cargo:https://github.com/jeffjose/mediainfo" = "latest"

# npm
"npm:@google/gemini-cli" = "latest"
"npm:sass" = "latest"
"npm:astro" = "latest"
"npm:postcss-cli" = "latest"
"npm:t-get" = "latest"
"npm:opencode-ai" = "latest"
"npm:@openai/codex" = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:vercel" = "latest"
"npm:@qwen-code/qwen-code" = "latest"
"npm:@beads/bd" = "latest"
ninja = "latest"
cmake = "latest"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["python"]

[settings.npm]
bun = true
